baseURL = "https://keeev.in"
title   = "Hey, I'm Kevin"
DefaultContentLanguage = "en"

theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

googleAnalytics = "UA-141734986-1"
disqusShortname = "keeev-in"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Kevin Hern√°ndez"

[blackfriday]
  hrefTargetBlank = true

#[taxonomies]
#  tag      = "tags"
#  category = ""

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Software developer, Python fan üêç."
  keywords = ""
  images = [""]

  imglogo= "https://avatars0.githubusercontent.com/u/5288503?s=460&v=4"
  homeSubtitle = "Software developer, Python fan üêç"
  homeSub = "This blog is about my thoughts/projects/ideas  üöÄ"
  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = "https://github.com/kevteg"

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"

  [params.logo]
    logoText     = "$ ~"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/keeevinh"

  [[params.social]]
    name = "email"
    url  = "mailto:kevteg05@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/kevteg"

  [[params.social]]
    name = "instagram"
    url  = "https://www.instagram.com/keeeevinh/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/keeeevin"

[languages]
  [languages.en]
    subtitle  = "Hey, I'm Kevin"
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [languages.fr]
    subtitle  = "Hey, I'm Kevin"
    weight    = 2
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
